### ISSUE TITLE
Unused code should be removed

### ISSUE THREAD

**Issue by jskvara** [jakubboucek/kirillova-skolka#20]
https://github.com/jakubboucek/kirillova-skolka/blob/aa3df4acf716cd9fad355e5f203c47f1dcc33559/www/tools/great-tool.php#L7

Nepoužívaný kód je lepší odebrat místo zakomentování. Zakomentovaný kód snižuje přehlednost kódu a často bývá neaktuální.
Historie úprav je uchována v gitu, takže předchozí verze je možné nalézt v historii gitu :)

**Comment by jakubboucek** [comment]
Good point @jskvara, asi je to zapomenutý pozůstatek z refaktoringu #15 – bylo jich tam víc a dokonce jsme to i v rámci téže lekce řešili: https://github.com/jakubboucek/kirillova-skolka/pull/16#discussion_r295710589

@BadKoldrysh prosím, příležitostně to vyhoď při vykonávání nějaké z Lesson.

## Tip
Když do commitu, který to bude opravovat napíšeš `closes #20`, tak to tuto Issue automaticky zavře, jakmile uděláš `push` na server *([learn more](https://help.github.com/en/articles/closing-issues-using-keywords))*.
